### ISSUE TITLE
again?!

### ISSUE THREAD

**Issue by lucyydotp** [TheDeveloperDen/information#6]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/35287819/160933462-36b87ea4-1b83-40f6-b524-ba1aafacf3af.png">
this is actually not funny anymore

**Comment by bristermitten** [comment]
reject discord, return to github issues Le 30 mars 2022 22:25, Lucy ***@***.***> a écrit :

this is actually not funny anymore
